name: Build and Test

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: BUild frontend
        working-directory: ./frontend
        run: npm run build
