name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  dependency-scan:
    needs: build
    uses: ./.github/workflows/scan.yml

  sonarqube:
    needs: dependency-scan
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    needs: sonarqube
    uses: ./.github/workflows/docker.yml
    with:
      backend_image: drxp-backend
      frontend_image: drxp-frontend
      tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  image-scan:
    needs: docker
    uses: ./.github/workflows/image-scan.yml
    with:
      backend_image: drxp-backend
      frontend_image: drxp-frontend
      tag: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}